Controllers/Admin/ParentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Mono.TextTemplating;
using School_Management_System.Data;
using School_Management_System.Models.Admin;

namespace School_Management_System.Controllers.Admin
{
    public class ParentController : Controller
    {
        private readonly ApplicationDbContext db;

        public ParentController(ApplicationDbContext _db)
        {
            db = _db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddParent()
        {
            var classList = db.Class.ToList();
            var studentsList = db.students.ToList();

            // Assuming you want to initialize the properties of AssignedSubjects
            var model = new Parent
            {
                StudentsList = studentsList, 
                ClassesList = classList
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddParent(Parent obj)
        {
            var classList = db.Class.ToList();
            var studentsList = db.students.ToList();
            var model = new Parent
            {
                StudentsList = studentsList,
                ClassesList = classList
            };

            ModelState.Remove("ClassId");
            ModelState.Remove("Class");
            ModelState.Remove("ClassesList");
            ModelState.Remove("StudentId");
            ModelState.Remove("Students");
            ModelState.Remove("StudentsList");
            ModelState.Remove("StudentName");
            ModelState.Remove("ClassName");

            if (ModelState.IsValid)
            {
                if (obj.ClassId <= 0 || obj.StudentId <= 0)
                {
                    TempData["error"] = "Please select both Student and Class";
                    ModelState.Remove("ClassId");
                    return View(model);
                }
                if (db.students.Any(c => c.Password == obj.Password) || db.Teachers.Any(c => c.Password == obj.Password) || db.Parents.Any(c => c.Password == obj.Password))
                {
                    ModelState.AddModelError("Password", "Password already exists.");
                    return View(model);
                }
                var existingParent = db.Parents.FirstOrDefault(p => p.StudentId == obj.StudentId && p.ClassId == obj.ClassId);

                if (existingParent != null)
                {
                    // Update existing parent record with new details
                    existingParent.ParentName = obj.ParentName;
                    existingParent.MobileNumber = obj.MobileNumber;
                    existingParent.ParentEmail = obj.ParentEmail;
                    existingParent.ParentAdress = obj.ParentAdress;
                    existingParent.Password = obj.Password;

                    db.SaveChanges();
                    TempData["success"] = "Parent details updated successfully";
                    return RedirectToAction("ViewAllClassesParents");
                }
                else
                {
                    var selectedStudentName = studentsList.FirstOrDefault(s => s.StudentId == obj.StudentId)?.StudentName;
                    var selectedClassName = classList.FirstOrDefault(c => c.ClassId == obj.ClassId)?.ClassName;

                    // Create a new parent record
                    var newParentDetails = new Parent
                    {
                        ParentId = obj.ParentId,
                        StudentId = obj.StudentId,
                        ClassId = obj.ClassId,
                        StudentName = selectedStudentName,
                        ClassName = selectedClassName,
                        ParentName = obj.ParentName,
                        MobileNumber = obj.MobileNumber,
                        ParentEmail = obj.ParentEmail,
                        ParentAdress = obj.ParentAdress,
                        Password = obj.Password
                    };

                    db.Parents.Add(newParentDetails);
                    db.SaveChanges();
                    TempData["success"] = "Parent Added Successfully";
                    return RedirectToAction("ViewAllClassesParents");
                }
            }

            return View(model);
        }

        public IActionResult GetStudents(int classId)
        {
            var students = db.students
                .Where(s => s.ClassId == classId)
                .Select(s => new { s.StudentId, s.StudentName })
                .ToList();

            return Json(students);
        }

        public IActionResult ViewAllClassesParents()
        {
            List<Classes> objList = db.Class.ToList();
            return View(objList);
        }

        public IActionResult ViewClassParents(int classId)
        {
            // Step 3: Retrieve the students of the specified class
            var studentsOfClass = db.students.Where(s => s.ClassId == classId) // Assuming there is a property ClassId in the Student model
                .ToList();

            // Step 4: Create a ViewModel to represent the student details
            var viewModel = new List<StudentDetails>(); // You may want to create a dedicated ViewModel for better organization

            foreach (var student in studentsOfClass)
            {
                var studentViewModel = new StudentDetails
                {
                    StudentId = student.StudentId,
                    StudentName = student.StudentName,
                    StudentRollNo = student.StudentRollNo

                    // Add other properties as needed
                };

                viewModel.Add(studentViewModel);
            }

            return View(viewModel);
        }

        public IActionResult ViewStudentParent(int studentId)
        {
            // Step 3: Retrieve the parent of the specified student
            var parentofSpecificStudent = db.Parents.Where(s => s.StudentId == studentId) // Assuming there is a property ClassId in the Student model
                .ToList();

            // Step 4: Create a ViewModel to represent the student details
            var viewModel = new List<Parent>(); // You may want to create a dedicated ViewModel for better organization

            foreach (var parent in parentofSpecificStudent)
            {
                var studentViewModel = new Parent
                {
                    ParentId = parent.ParentId,
                    StudentId = parent.StudentId,
                    StudentName = parent.StudentName,
                    ParentName= parent.ParentName,
                    MobileNumber = parent.MobileNumber,
                    ParentEmail = parent.ParentEmail,
                    ParentAdress = parent.ParentAdress,
                    Password = parent.Password,
                    ClassId = parent.ClassId,
                    ClassName= parent.ClassName,
                };

                viewModel.Add(studentViewModel);
            }

            return View(viewModel);
        }

        public IActionResult EditParent(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            Parent? categoryFromDb = db.Parents.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        [HttpPost]
        public IActionResult EditParent(Parent obj)
        {
            ModelState.Remove("ClassId");
            ModelState.Remove("Class");
            ModelState.Remove("ClassesList");
            ModelState.Remove("StudentId");
            ModelState.Remove("Students");
            ModelState.Remove("StudentsList");
            ModelState.Remove("StudentName");
            ModelState.Remove("ClassName");

            var classList = db.Class.ToList();
            var studentsList = db.students.ToList();
            var model = new Parent
            {
                StudentsList = studentsList,
                ClassesList = classList
            };

            if (ModelState.IsValid)
            {
                if (db.students.Any(c => c.Password == obj.Password) || db.Teachers.Any(c => c.Password == obj.Password) || db.Parents.Any(c => c.Password == obj.Password))
                {
                    ModelState.AddModelError("Password", "Password already exists.");
                    return View(model);
                }


                var existingParent = db.Parents.FirstOrDefault(p =>  p.ParentId == obj.ParentId);

                if (existingParent != null)
                {
                    // Update existing parent record with new details
                    existingParent.ParentName = obj.ParentName;
                    existingParent.MobileNumber = obj.MobileNumber;
                    existingParent.ParentEmail = obj.ParentEmail;
                    existingParent.ParentAdress = obj.ParentAdress;
                    existingParent.Password = obj.Password;

                    db.SaveChanges();
                    TempData["success"] = "Parent Updated Successfully";
                    return RedirectToAction("ViewAllClassesParents");
                }

            }

            return View(model);
        }

        public IActionResult DeleteParent(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            Parent? categoryFromDb = db.Parents.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //Delete the Parent
        [HttpPost, ActionName("DeleteParent")]
        public IActionResult DeleteParent(int? id)
        {
            var parentToDelete = db.Parents.Find(id);

            if (parentToDelete != null)
            {

Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School_Management_System.Data;
using School_Management_System.Models;




namespace School_Management_System.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly ApplicationDbContext db;

        public AuthenticationController(ApplicationDbContext _db)
        {
            db = _db;
        }

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Login loginModel)
        {
            var existingAdmin = db.AdminCredential.FirstOrDefault(admin => admin.Email == loginModel.Email && admin.Password == loginModel.Password);
            var existingTeacher = db.Teachers.FirstOrDefault(teacher => teacher.TeacherEmail == loginModel.Email && teacher.Password == loginModel.Password);
            var existingStudent = db.students.FirstOrDefault(student => student.StudentEmail == loginModel.Email && student.Password == loginModel.Password);
            var existingParent = db.Parents.FirstOrDefault(parent => parent.ParentEmail == loginModel.Email && parent.Password == loginModel.Password);

            if (ModelState.IsValid && existingAdmin != null)
            {
                return RedirectToAction("Index", "Dashboard");
            }
            else if (ModelState.IsValid && existingTeacher != null)
            {
                HttpContext.Session.SetString("TeacherEmail", existingTeacher.TeacherEmail.ToString());
                return RedirectToAction("Index", "TeacherDashboard");
            }
            else if (ModelState.IsValid && existingStudent != null)
            {
                HttpContext.Session.SetString("StudentEmail", existingStudent.StudentEmail.ToString());
                return RedirectToAction("Index", "StudentDashboard");
            }
            else if (ModelState.IsValid && existingParent != null)
            {
                HttpContext.Session.SetString("ParentEmail", existingParent.ParentEmail.ToString());
                return RedirectToAction("Index", "ParentDashboard");
            }

            // If ModelState is not valid or login fails, return to the login view
            TempData["error"] = "Invalid Email or Password";
            ModelState.Clear();
            return View("Login");
        }


        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

Views/Shared/Error - Copy.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon.png">
    <title>Matrix Template - The Ultimate Multipurpose admin template</title>
    <!--  Toaster Notifications-->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <!-- Custom CSS -->
    <link href="~/assets/libs/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet" />
    <link href="~/assets/extra-libs/calendar/calendar.css" rel="stylesheet" />
    <link href="~/dist/css/style.min.css" rel="stylesheet">
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper">
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    <a asp-action="Index" asp-controller="Dashboard" class="navbar-brand">
                        <!-- Logo icon -->
                        <b class="logo-icon p-l-10">
                            <img src="~/assets/images/logo-icon.png" alt="homepage" class="light-logo" />
                        </b>
                        <span class="logo-text">
                            <!-- dark Logo text -->
                            <img src="~/assets/images/logo-text.png" alt="homepage" class="light-logo" />
                        </span>
                    </a>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                
            </nav>
        </header>
        <aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">

                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-school"></i><span class="hide-menu">Class </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href='@Url.Action("ViewClasses", "Class")' class="sidebar-link"><i class="fas fa-users"></i><span class="hide-menu">View All Classes</span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("ViewAllSubjects","Class")' class="sidebar-link"><i class="fas fa-book"></i><span class="hide-menu">View All Subjects </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("CreateClass", "Class")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Add Class </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("AddSubjects", "Class")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Add Subject </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("ViewFees","Class")' class="sidebar-link"><i class="fas fa-list-alt"></i><span class="hide-menu"> Fee Setup </span></a></li>
                            </ul>
                        </li>


                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-user-graduate"></i><span class="hide-menu">Student </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href='@Url.Action("ViewAllStudents", "Student")' class="sidebar-link"><i class="fas fa-users"></i><span class="hide-menu">View All Students</span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("AddStudent", "Student")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Add Student </span></a></li>
                            </ul>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-users-cog"></i><span class="hide-menu">Staff </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href='@Url.Action("ViewTeachers", "Teacher")' class="sidebar-link"><i class="fas fa-users"></i><span class="hide-menu">View All Staff</span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("AddTeacher", "Teacher")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Add Staff </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("AssignSubject", "Teacher")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Assign Subject </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("ViewAssignSubjects", "Teacher")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu">View Assigned Subjects </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("ViewSalaries", "Teacher")' class="sidebar-link"><i class="fab fa-amazon-pay"></i><span class="hide-menu"> Staff Salary </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("ViewAllStaffAttendance", "Teacher")' class="sidebar-link"><i class="fas fa-street-view"></i><span class="hide-menu"> Attendance </span></a></li>
                            </ul>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-users-cog"></i><span class="hide-menu">Parents </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href='@Url.Action("ViewAllClassesParents", "Parent")' class="sidebar-link"><i class="fas fa-users"></i><span class="hide-menu">View All Parents</span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("AddParent", "Parent")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Add Parent </span></a></li>
                            </ul>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-list-alt"></i><span class="hide-menu">Finance</span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href='@Url.Action("ViewExpenditures", "Expenditure")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu">View Expenditures</span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("CreateExpenditure", "Expenditure")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> Add Expenditures </span></a></li>
                                <li class="sidebar-item"><a href='@Url.Action("ViewIncome", "Expenditure")' class="sidebar-link"><i class="fas fa-arrow-alt-circle-right"></i><span class="hide-menu"> View Income </span></a></li>
                            </ul>
                        </li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href='@Url.Action("Login", "Authentication")' aria-expanded="false"><i class="fas fa-sign-out-alt"></i><span class="hide-menu">Logout</span></a></li>
                    </ul>
                </nav>
            </div>
        </aside>
        <partial name="_NotificationLayout" />
        @RenderBody()
    </div>
    <script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/dist/js/jquery.ui.touch-punch-improved.js"></script>
    <script src="~/dist/js/jquery-ui.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/assets/extra-libs/sparkline/sparkline.js"></script>
    <!--Wave Effects -->
    <script src="~/dist/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="~/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/dist/js/custom.min.js"></script>
    <!-- this page js -->
    <script src="~/assets/libs/moment/min/moment.min.js"></script>
    <script src="~/assets/libs/fullcalendar/dist/fullcalendar.min.js"></script>
    <script src="~/dist/js/pages/calendar/cal-init.js"></script>
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NotificationLayout.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon.png">
    <title>Matrix Template - The Ultimate Multipurpose admin template</title>
    <!--  Toaster Notifications-->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <!-- Custom CSS -->
    <link href="~/assets/libs/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet" />
    <link href="~/assets/extra-libs/calendar/calendar.css" rel="stylesheet" />
    <link href="~/dist/css/style.min.css" rel="stylesheet">
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper">
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    <a class="navbar-brand" href="index.html">
                        <!-- Logo icon -->
                        <b class="logo-icon p-l-10">
                            <img src="~/assets/images/logo-icon.png" alt="homepage" class="light-logo" />

                        </b>
                        <span class="logo-text">
                            <!-- dark Logo text -->
                            <img src="~/assets/images/logo-text.png" alt="homepage" class="light-logo" />
                        </span>
                    </a>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>

            </nav>
        </header>
        <aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href='@Url.Action("Index","StudentDashboard")' aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href='@Url.Action("ViewSubjects", "StudentDashboard")' aria-expanded="false"><i class="fas fa-book"></i><span class="hide-menu">View Subjects</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href='@Url.Action("ViewMaterials", "StudentDashboard")' aria-expanded="false"><i class="fas fa-book"></i><span class="hide-menu">View Learning Material</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href='@Url.Action("ViewAttendance", "StudentDashboard")' aria-expanded="false"><i class="fas fa-book"></i><span class="hide-menu">View Attendance Record</span></a></li>

                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href='@Url.Action("Login", "Authentication")' aria-expanded="false"><i class="fas fa-sign-out-alt"></i><span class="hide-menu">Logout</span></a></li>

                    </ul>
                </nav>
            </div>
        </aside>
        <partial name="_NotificationLayout" />
        @RenderBody()
    </div>
    <script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/dist/js/jquery.ui.touch-punch-improved.js"></script>
    <script src="~/dist/js/jquery-ui.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/assets/extra-libs/sparkline/sparkline.js"></script>
    <!--Wave Effects -->
    <script src="~/dist/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="~/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/dist/js/custom.min.js"></script>
    <!-- this page js -->
    <script src="~/assets/libs/moment/min/moment.min.js"></script>
    <script src="~/assets/libs/fullcalendar/dist/fullcalendar.min.js"></script>
    <script src="~/dist/js/pages/calendar/cal-init.js"></script>
    @* @Scripts .Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap") *@
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>