Models/Admin/Expenditures.cs
using System.ComponentModel.DataAnnotations;

namespace School_Management_System.Models.Admin
{
    public class Expenditures
    {
        [Key]
        public int ExpenditureId { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string ExpenditureTitle { get; set; }

        [Required]
        [Range(1,int.MaxValue)]
        public int ExpenditureAmount { get; set; }

        [Required(ErrorMessage = "The Date field is required.")]
        public DateOnly Date { get; set; }

        public TimeOnly Time { get; set; }

    }
}

Controllers/Admin/ExpenditureController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School_Management_System.Data;
using School_Management_System.Models.Admin;

namespace School_Management_System.Controllers.Admin
{
    public class ExpenditureController : Controller
    {
        private readonly ApplicationDbContext db;

        public ExpenditureController(ApplicationDbContext _db)
        {
            db = _db;
        }
        public IActionResult ViewExpenditures()
        {
            // Get all expenditures from the database
            List<Expenditures> objList = db.Expenditure.ToList();

            // Calculate the sum of all expenditure amounts
            decimal totalExpenditure = objList.Sum(e => e.ExpenditureAmount);

            // Pass the total expenditure along with the list of expenditures to the view
            ViewBag.SumOfAllExpenditures = totalExpenditure;
            return View(objList);
        }

        public IActionResult CreateExpenditure()
        {
            return View();
        }

        //Create or Add New Expenditure
        [HttpPost]
        public IActionResult CreateExpenditure(Expenditures obj)
        {
            if (ModelState.IsValid)
            {
                if (db.Expenditure.Any(c => c.ExpenditureTitle == obj.ExpenditureTitle&&c.Date==obj.Date && c.Time == obj.Time))
                {
                    ModelState.AddModelError("ExpenditureTitle", "Same Title Name on Same Date and time already exists.");
                    return View();
                }
                obj.Time = TimeOnly.FromDateTime(DateTime.Now);
                db.Expenditure.Add(obj);
                db.SaveChanges();
                TempData["success"] = "Created Successfully";
                return RedirectToAction("ViewExpenditures");
            }
            return View();
        }


        //Edit the Expenditure
        public IActionResult EditExpenditure(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            Expenditures? categoryFromDb = db.Expenditure.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }


        [HttpPost]
        public IActionResult EditExpenditure(Expenditures obj)
        {
            if (ModelState.IsValid)
            {
                if (db.Expenditure.Any(c => c.ExpenditureTitle == obj.ExpenditureTitle && c.Date == obj.Date && c.Time == obj.Time))
                {
                    ModelState.AddModelError("ExpenditureTitle", "Same Title Name on Same Date and time already exists.");
                    return View();
                }

                // Retrieve the original Expenditure
                var originalExpenditure = db.Expenditure.Find(obj.ExpenditureId);

                if (originalExpenditure != null)
                {
                    // Update Expenditure information
                    originalExpenditure.ExpenditureTitle = obj.ExpenditureTitle;
                    originalExpenditure.ExpenditureAmount = obj.ExpenditureAmount;
                    originalExpenditure.Date = obj.Date;
                    originalExpenditure.Time = TimeOnly.FromDateTime(DateTime.Now); ;
                    db.SaveChanges();
                    TempData["success"] = "Expenditure Updated Successfully";
                }
                else
                {
                    TempData["error"] = "Expenditure not found";
                }

                return RedirectToAction("ViewExpenditures");
            }

            return View();
        }


        //Delete the Expenditure
        public IActionResult DeleteExpenditure(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            Expenditures? categoryFromDb = db.Expenditure.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //Delete the Expenditure
        [HttpPost, ActionName("DeleteExpenditure")]
        public IActionResult DeleteExpenditures(int? id)
        {
            Expenditures? obj = db.Expenditure.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            db.Expenditure.Remove(obj);
            db.SaveChanges();
            TempData["success"] = "Expenditure Deleted Successfully";
            return RedirectToAction("ViewExpenditures");

        }


        public IActionResult ViewIncome()
        {
            var classDetails = db.Class
        .GroupJoin(db.students,
            c => c.ClassId,
            s => s.ClassId,
            (c, students) => new
            {
                ClassName = c.ClassName,
                NumberOfStudents = students.Count(),
                FeeAmount = db.fees.FirstOrDefault(f => f.ClassId == c.ClassId) // Get the FeeAmount without using the null-conditional operator
            })
        .Select(x => new ClassWithStudentCount
        {
            ClassName = x.ClassName,
            StudentCount = x.NumberOfStudents,
            ClassIncome = x.FeeAmount != null ? x.NumberOfStudents * x.FeeAmount.FeeAmount : 0 // Calculate class income
        })
        .ToList();

            // Calculate the sum of all classes' income
            var totalIncome = classDetails.Sum(x => x.ClassIncome);

            // Set the TotalIncome property in each class detail
            foreach (var detail in classDetails)
            {
                detail.TotalIncome = totalIncome;
            }
            ViewBag.SumOfAllClassesIncome = totalIncome;
            return View(classDetails);
        }
    }
}

Views/Expenditure/CreateExpenditure.cshtml
@model School_Management_System.Models.Admin.Expenditures

@{
    ViewData["Title"] = "CreateExpenditure";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-wrapper">

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Create Expenditures</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">

        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fas fa-level-up-alt"></i>Create Expenditures</h5>
                    </div>

                    <div class="row">
                        <div class=" card-body">
                            <form asp-controller="Expenditure" asp-action="CreateExpenditure" method="post">

                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <label asp-for="ExpenditureTitle" class="control-label col-md-2"></label>
                                        <div class="col-md-10">
                                            <input asp-for="ExpenditureTitle" class="form-control" />
                                            <span asp-validation-for="ExpenditureTitle" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="ExpenditureAmount" class="control-label col-md-2"></label>
                                        <div class="col-md-10">
                                            <input asp-for="ExpenditureAmount" class="form-control" />
                                            <span asp-validation-for="ExpenditureAmount" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="Date" class="control-label col-md-2"></label>
                                        <div class="col-md-10">
                                            <input asp-for="Date" type="date" class="form-control" />
                                            <span asp-validation-for="Date" class="text-danger"></span>
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <button type="submit" class="btn btn-default">Create</button>
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>







<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Expenditure/DeleteExpenditure.cshtml
@model School_Management_System.Models.Admin.Expenditures

@{
    ViewData["Title"] = "DeleteExpenditure";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-wrapper">
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Expenditure</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Delete Expenditures</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">

        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title m-b-0"><i class="fas fa-calendar-alt"></i> Are you sure you want to delete this?</h3>
                    </div>

                    <div class="row">
                        <div class=" card-body">

                            <div class="form-horizontal">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="ExpenditureTitle" class="control-label col-md-4"></label>
                                            <span asp-for="ExpenditureTitle" class="form-control">@Model.ExpenditureTitle</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="ExpenditureAmount" class="control-label col-md-4"></label>
                                            <span asp-for="ExpenditureAmount" class="form-control">@Model.ExpenditureAmount</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="Date" class="control-label col-md-4"></label>
                                            <span asp-for="Date" class="form-control">@Model.Date</span>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <form asp-action="DeleteExpenditure">
                                        <input type="hidden" asp-for="ExpenditureId" />
                                        <input type="submit" value="Delete" class="btn btn-danger" />
                                        <a asp-action="ViewExpenditures" class="btn btn-default">Back to List</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Views/Expenditure/EditExpenditure.cshtml
@model School_Management_System.Models.Admin.Expenditures

@{
    ViewData["Title"] = "EditExpenditure";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-wrapper">

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit Expenditure</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">

        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fas fa-calendar-alt"></i> Edit Class</h5>
                    </div>

                    <div class="row">
                        <div class=" card-body">
                            <form asp-controller="Expenditure" asp-action="EditExpenditure" method="post">

                                <div class="form-horizontal">
                                    <input asp-for="ExpenditureId" type="hidden" />

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label asp-for="ExpenditureTitle" class="control-label col-md-3"></label>
                                                <input asp-for="ExpenditureTitle" class="form-control" />
                                                <span asp-validation-for="ExpenditureTitle" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="ExpenditureAmount" class="control-label col-md-2"></label>
                                        <div class="col-md-10">
                                            <input asp-for="ExpenditureAmount" class="form-control" />
                                            <span asp-validation-for="ExpenditureAmount" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="Date" class="control-label col-md-2"></label>
                                        <div class="col-md-10">
                                            <input asp-for="Date" type="date" class="form-control" />
                                            <span asp-validation-for="Date" class="text-danger"></span>
                                        </div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-default">Update</button>
                                        <a asp-action="ViewExpenditures" asp-controller="Expenditure" class="btn btn-default">Back to List</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Expenditure/ViewExpenditures.cshtml
@model IEnumerable<School_Management_System.Models.Admin.Expenditures>

@{
    ViewBag.Title = "ViewExpenditures";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-wrapper">

    <div class="page-breadcrumb">

        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Expenditures</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">View Expenditures</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="row">
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            <label>Expenditure Title</label>
                                        </th>
                                        <th>
                                            <label>Amount</label>
                                        </th>
                                        <th>
                                            <label>Action</label>
                                        </th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ExpenditureTitle)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ExpenditureAmount)
                                        </td>
                                        <td>
                                            <a asp-action="EditExpenditure" asp-controller="Expenditure" asp-route-id="@item.ExpenditureId" class="btn btn-mini btn-outkine-orange icon-edit bigger-10">
                                                <img src="~/assets/48763_file_edit_icon.png" />
                                            </a>

                                            <a asp-action="DeleteExpenditure" asp-controller="Expenditure" asp-route-id="@item.ExpenditureId" class="btn btn-mini btn-outkine-orange icon-edit bigger-10">
                                                <img src="~/assets/616650_bin_delete_garbage_trash_icon.png" />
                                            </a>

                                        </td>
                                    </tr>
                                }

                            </table>

                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            <label>Total Expenditures</label>
                                        </th>
                                        <th>
                                            <label> @ViewBag.SumOfAllExpenditures</label>
                                        </th>
                                    </tr>

                                </thead>

                            </table>


                            <style>
                                .pagination {
                                    display: inline-block;
                                }

                                    .pagination a {
                                        color: black;
                                        float: left;
                                        padding: 8px 16px;
                                        text-decoration: none;
                                    }

                                        .pagination a.active {
                                            background-color: #4CAF50;
                                            color: white;
                                        }

                                        .pagination a:hover:not(.active) {
                                            background-color: #ddd;
                                        }
                            </style>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
        function Delete(id) {
            alertify.confirm('Matrix International School', 'Are you sure?', function () {
                window.location.href = '@Url.Action("DeleteSession", "Settings")/' + id;
            }, null);
        }
    </script>

}

Views/Expenditure/ViewIncome.cshtml
@model IEnumerable<School_Management_System.Models.Admin.ClassWithStudentCount>

@{
    ViewBag.Title = "ViewIncome";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-wrapper">

    <div class="page-breadcrumb">

        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Income</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">View Income</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="row">
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            <label>ClassName</label>
                                        </th>
                                        <th>
                                            <label>StudentsCount</label>
                                        </th>
                                        <th>
                                            <label>Income</label>
                                        </th>
                                    </tr>
                                    
                                </thead>
                                
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StudentCount)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassIncome)
                                        </td>
                                    </tr>
                                }

                            </table>

                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            <label>Total Income</label>
                                        </th>
                                        <th>
                                            <label> @ViewBag.SumOfAllClassesIncome</label>
                                        </th>
                                    </tr>

                                </thead>

                            </table>

                            <style>
                                .pagination {
                                    display: inline-block;
                                }

                                    .pagination a {
                                        color: black;
                                        float: left;
                                        padding: 8px 16px;
                                        text-decoration: none;
                                    }

                                        .pagination a.active {
                                            background-color: #4CAF50;
                                            color: white;
                                        }

                                        .pagination a:hover:not(.active) {
                                            background-color: #ddd;
                                        }
                            </style>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
        function Delete(id) {
            alertify.confirm('Matrix International School', 'Are you sure?', function () {
                window.location.href = '@Url.Action("DeleteSession", "Settings")/' + id;
            }, null);
        }
    </script>

}